@startuml

actor User
participant "Click App" as CA
participant "MiniApp Partner" as miniPartner
participant "Click Evolution" as CE
participant "Click BNPL" as CBNPL
database "Click BNPL DB" as CBNPLDB
participant "Click Acquiring" as CAcquiring
participant "Partner backend" as partnerBack



== Click-Комплит, отрисовка виджета ==

User -> CA: Checkout page
CA -> CE : Создать заказ(click_user_id, корзина)
CE -> CBNPL : Создать заказ(click_user_id, корзина)
CBNPL -> CBNPL: Прескор клиента (Проверка на белый лист)
CBNPL -> CBNPL: Проверка доступности параметры мерчанта 
alt (отказ) Не прошел прескор 
CBNPL --> CE: через Partner невозможно платить
CE --> CA: Отказ
CA --> User: Отказ / Может платить другим способом
else (успешно) Прошел прескор
CBNPL -> CBNPL : Сгенерировать checkout_id
CBNPL -> partnerBack : Создать заказ(checkout_id, click_user_id, корзина)
partnerBack -> partnerBack : Сохранить(checkout_id, click_user_id) 
partnerBack -> partnerBack: Проверка доступности лимита клиента

alt (отказ) Не прошел проверку
partnerBack --> CBNPL: Не прошел проверку (отказ)
CBNPL --> CE: через Partner невозможно платить
CE --> CA: Отказ
CA --> User: Отказ / Может платить другим способом

else (успешно) Прошел проверку
partnerBack --> CBNPL: Прошел проверку (Вернуть планы)
CBNPL ->> CBNPLDB: Commit checkout_id
CBNPL --> CE: Заказ создан, планы списаний
CE --> CA: Заказ создан, планы списаний
CA --> User: Виджет с планами

== Оформление Partner ==

User -> CA: Оформить Partner
CA -> CE: payWithPartner(checkout_id, click_card_id, \nprovider_id)

CE -> CBNPL: /pay (checkout_id, click_card_id)
CBNPL ->> miniPartner: Редирект клиента в миниапп Partner
miniPartner --> User: Показывает лоадер
miniPartner -> partnerBack: Запрос на подтверждение оформление Partner
partnerBack -> partnerBack: Проверка наличие лимита клиента
alt (ошибка/отказ) Не прошел проверку
partnerBack --> miniPartner: Показывает ответ в миниапп на миниапп | Ошибка при платеже \n+причина ошибки
miniPartner --> User: Ошибка при платеже / Показывает причину ошибки
else (успешно) Можно провести первый платеж
partnerBack -> CBNPL: POST \n/api/bnpl/partner/v1/payment \nотправляет 0 сум
CBNPL -> CAcquiring: Проведи платеж
CAcquiring -> CAcquiring: Авторизация (click_user_id, click_card_id)
CAcquiring -> CAcquiring: Проведет первый платеж
alt Неизвестная ошибка(со статусом 500) при проведение платежа
CAcquiring --> CBNPL: Ошибка при платеже \n+причина ошибки
CBNPL --> partnerBack: Отправит статус платежа в ответе \nОшибка при платеже \n+причина ошибки
partnerBack -> CBNPL: GET \n/api/bnpl/general/v2/payment/state
CBNPL -> CBNPL: Get payment status from click core system
CBNPL --> partnerBack: Payment status
alt ошибка(со статусом 500)
partnerBack --> miniPartner: Показывает ответ в миниапп на миниапп | Ошибка при платеже \n+причина ошибки
miniPartner --> User: Ошибка при платеже / Показывает причину ошибки
else status = 2 (со статусом 200)
partnerBack --> miniPartner: Показывает ответ в миниапп | Partner успешно оформлен
miniPartner --> User: Partner успешно оформлен
end
else Ошибка(со статусом 200) при проведение платежа
CAcquiring --> CBNPL: Ошибка при платеже \n+причина ошибки
CBNPL --> partnerBack: Отправит статус платежа в ответе \nОшибка при платеже \n+причина ошибки
partnerBack -> CBNPL: GET \n/api/bnpl/general/v2/payment/state
CBNPL -> CBNPL: Get payment status from click core system
CBNPL --> partnerBack: Payment status
alt ошибка(со статусом 500)
partnerBack --> miniPartner: Показывает ответ в миниапп на миниапп | Ошибка при платеже \n+причина ошибки
miniPartner --> User: Ошибка при платеже / Показывает причину ошибки
else status = 2 (со статусом 200)
partnerBack --> miniPartner: Показывает ответ в миниапп | Partner успешно оформлен
miniPartner --> User: Partner успешно оформлен
end
else Платеж проведен успешно
CAcquiring --> CBNPL: Платеж проведен
CBNPL -> CBNPLDB: Сохранить платеж
CBNPL --> partnerBack: Отправит статус платежа в ответе
partnerBack --> miniPartner: Показывает ответ в миниапп | Partner успешно оформлен
miniPartner --> User: Partner успешно оформлен

end
end
end
end

@enduml
